<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjut</name>
   <tag></tag>
   <elementGuidId>0ec818b7-992a-45b1-a76f-5132aea6e86d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ButtonContainer-component__ButtonContainer.ButtonContainer-component__spaceBetween.ButtonContainer-component__space-md > button.Button-component__button.Button-component__primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f2c55ba-144b-40d1-9166-46a60e53132b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button-component__button Button-component__primary</value>
      <webElementGuid>519c0566-aab1-4913-8cd7-d4025885cf09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>217761c2-3f71-43c3-b973-8bd5401b05cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjut</value>
      <webElementGuid>1e8dce66-40d7-4f79-90ea-d4f483aab5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;Customer-layout__appLayout&quot;]/div[@class=&quot;Customer-layout__container&quot;]/div[@class=&quot;Customer-layout__content Customer-layout__notDashboard&quot;]/div[@class=&quot;AddOffer-component__addOfferComponent&quot;]/form[@class=&quot;AddOffer-component__addOfferFormComponent&quot;]/div[@class=&quot;ButtonContainer-component__ButtonContainer ButtonContainer-component__spaceBetween ButtonContainer-component__space-md&quot;]/button[@class=&quot;Button-component__button Button-component__primary&quot;]</value>
      <webElementGuid>10bcbe29-0061-4dbd-aad6-8ae6c4615540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>85916850-b04a-449c-ace3-b50ed26b2d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/form/div[3]/button[2]</value>
      <webElementGuid>dc04a84c-5daf-4f25-a05b-7f362cde866c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::button[1]</value>
      <webElementGuid>75c21760-5421-406d-9a8b-14c5214b0205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket'])[1]/following::button[2]</value>
      <webElementGuid>f465b577-41c3-4b30-a472-138a683b8400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current interaction'])[1]/preceding::button[1]</value>
      <webElementGuid>4e92be69-543d-4bba-9929-e3a8c2974c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Cases'])[1]/preceding::button[2]</value>
      <webElementGuid>b5749f7a-e089-465a-a782-f578b1382eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjut']/parent::*</value>
      <webElementGuid>b4604470-3f2a-4f60-9888-836b8a5c1d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>bc47d248-4181-4f75-86b6-b677458af59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Lanjut' or . = 'Lanjut')]</value>
      <webElementGuid>7f1114d1-70c5-4fa7-a2b3-eea9233d2edf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
