<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>971056cb-80e8-44ce-94b1-25dbab659210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.AgentLogin-component__loginBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36e982a7-aa36-4eb3-b13f-4a7b509ff200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c831a915-aa6f-494c-8ecc-be3a1d9ccc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AgentLogin-component__loginBtn</value>
      <webElementGuid>faaca709-69cd-42a7-acf3-dbc558f1d5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>766e2668-95f3-48d7-95a2-79d2516d63e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;Login-layout__loginLayoutWrapper&quot;]/div[@class=&quot;Login-layout__loginLayout&quot;]/div[@class=&quot;LoginAgent-container__loginContainer&quot;]/div[@class=&quot;LoginAgent-container__loginImageSection&quot;]/div[@class=&quot;LoginAgent-container__twoColumns&quot;]/div[@class=&quot;LoginAgent-container__second&quot;]/div[@class=&quot;LoginAgent-container__loginFormSection&quot;]/div[@class=&quot;LoginAgent-container__loginFormContainer&quot;]/div[@class=&quot;LoginAgent-container__loginFormContent&quot;]/div[@class=&quot;AgentLogin-component__agentLoginComponent&quot;]/form[@class=&quot;AgentLogin-component__agentLoginFormComponent&quot;]/div[@class=&quot;AgentLogin-component__loginBtnContainer&quot;]/button[@class=&quot;AgentLogin-component__loginBtn&quot;]</value>
      <webElementGuid>402e7b71-7951-43f4-a006-9d556d554ea1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>099e0b2b-9502-4a59-9544-6303e9e52584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/form/div[2]/button</value>
      <webElementGuid>af058cac-213f-4ad5-b0d6-ebb0d30327b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setuju dengan ketentuan yang berlaku'])[1]/following::button[1]</value>
      <webElementGuid>c17717e3-b905-4343-beb7-9682648c9a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk menggunakan'])[1]/following::button[1]</value>
      <webElementGuid>e9b879b7-5664-469b-9a57-f4cbd4852ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>feaee198-70c6-404d-bd8c-ab8581f85aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>96371c05-3de3-4243-b3ef-ff9ae70d4f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
