<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>23644a13-5344-44cb-a3f4-6a91a820fb35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Popup-container__defaulActionBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6730a90f-4a7d-474b-9d09-efefc60c3b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Popup-container__defaulActionBtn</value>
      <webElementGuid>f192c4d9-086c-4829-9656-620367c632ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>4dc954ac-e98f-4054-9beb-29bbfe31b503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;Popup-container__popupContainer Popup-container__open&quot;]/div[@class=&quot;Popup-container__popupContent&quot;]/div[@class=&quot;Popup-container__footer&quot;]/button[@class=&quot;Popup-container__defaulActionBtn&quot;]</value>
      <webElementGuid>b12ab163-2863-4011-a439-8f32a7ad82e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e1541c57-7b39-4710-82a8-6cd1711bc44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button-component__button Button-component__primary</value>
      <webElementGuid>dfdc8120-8a8b-44fa-833c-8cc9efcf462f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62db663c-b8f7-4b11-8363-23838d287eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>f40d791e-8139-41c6-8a23-d7a762f8af21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ReactModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open Modal-component__modalOverlay&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open Modal-component__modal Modal-component__large1&quot;]/div[@class=&quot;Modal-component__container&quot;]/div[@class=&quot;Modal-component__content&quot;]/div[@class=&quot;ButtonContainer-component__ButtonContainer ButtonContainer-component__center ButtonContainer-component__space-md&quot;]/button[@class=&quot;Button-component__button Button-component__primary&quot;]</value>
      <webElementGuid>7054514c-616e-4193-a517-f7dbd1e1e593</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[3]/button</value>
      <webElementGuid>6667c10b-95f8-4e95-9af9-f7ef244b7267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telkomsel.com'])[1]/preceding::button[1]</value>
      <webElementGuid>83332bed-b9e2-473c-b96f-d359e91db8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b315f025-79cd-4442-9606-9c669030c52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>c42e3fee-ce4e-4fac-b9b9-6723fd5c0a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>70d0e47e-5733-4394-b2f0-5fbf02511578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klik disini untuk menunjukkan Anda telah membaca dan menyetujui Syarat dan Ketentuan'])[1]/following::button[1]</value>
      <webElementGuid>9bcaaf56-eb6a-49c8-82ed-0a8d7c65d10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya setuju'])[1]/following::button[1]</value>
      <webElementGuid>c680d9e1-4646-452f-bd50-84c5c34e860e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>f7d085bf-f5af-4a9d-9485-4ba6a4349964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>5bdab530-c987-4a90-9120-e81d74661eae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
