<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masuk menggunakan_password</name>
   <tag></tag>
   <elementGuidId>1578306c-d8b0-4810-a1dc-3540160efabf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55926720-39ee-4506-9ac9-006158999a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8b865cbe-e256-4d32-8364-ae3210917812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AgentLogin-component__formControl</value>
      <webElementGuid>c3166824-e768-4647-aafa-fb681be2d0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kata sandi Anda</value>
      <webElementGuid>166a69bd-14a8-4da4-92e8-452d65e9b4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8f2ff5e1-1010-4c02-b267-5f0cdc25c63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>47e7d357-df19-4e9b-bb3c-717730161b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>k</value>
      <webElementGuid>849e9f03-8fe4-4207-b213-43292de2fad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;Login-layout__loginLayoutWrapper&quot;]/div[@class=&quot;Login-layout__loginLayout&quot;]/div[@class=&quot;LoginAgent-container__loginContainer&quot;]/div[@class=&quot;LoginAgent-container__loginImageSection&quot;]/div[@class=&quot;LoginAgent-container__twoColumns&quot;]/div[@class=&quot;LoginAgent-container__second&quot;]/div[@class=&quot;LoginAgent-container__loginFormSection&quot;]/div[@class=&quot;LoginAgent-container__loginFormContainer&quot;]/div[@class=&quot;LoginAgent-container__loginFormContent&quot;]/div[@class=&quot;AgentLogin-component__agentLoginComponent&quot;]/form[@class=&quot;AgentLogin-component__agentLoginFormComponent&quot;]/div[@class=&quot;AgentLogin-component__inputLogin&quot;]/fieldset[@class=&quot;AgentLogin-component__formGroup&quot;]/input[@class=&quot;AgentLogin-component__formControl&quot;]</value>
      <webElementGuid>34f6a0f6-af0c-4ad3-ad94-7c476bda8a79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>8d53c7c6-d46d-42f5-8a60-9062f214e767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/form/div/fieldset[2]/input</value>
      <webElementGuid>f23251c4-b1cb-413c-9392-8d2603cd7ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk menggunakan'])[1]/following::input[2]</value>
      <webElementGuid>f3f89d39-eea9-4d9f-ba55-6f6f56fb2fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kepentingan pribadi'])[1]/following::input[2]</value>
      <webElementGuid>b5b4cc7b-f399-4f89-aa36-aad747c28535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setuju dengan ketentuan yang berlaku'])[1]/preceding::input[1]</value>
      <webElementGuid>72163222-d07b-4831-b751-f3f14fd3f74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::input[1]</value>
      <webElementGuid>7502c450-b963-4907-b302-cecec3de6e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/input</value>
      <webElementGuid>46dd819d-cb44-4227-a590-7ba8bdb6b006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Kata sandi Anda' and @name = 'password']</value>
      <webElementGuid>c43e1f6b-b7ef-45fb-93ba-cd696cebf12c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
