<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masuk menggunakan_email</name>
   <tag></tag>
   <elementGuidId>5bdb0f66-a625-4f38-90df-e68a5614a117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7385584b-5f30-4953-bf43-52304049141d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AgentLogin-component__formControl</value>
      <webElementGuid>72985478-e685-4cab-b3b2-056db84db6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Username</value>
      <webElementGuid>0fef828b-428a-4db2-8ea5-92e2d3ab618d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>72e4194b-bab2-421a-a3ed-a8a8473f113e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>188ee2de-2d26-47a6-9796-274bff813cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;Login-layout__loginLayoutWrapper&quot;]/div[@class=&quot;Login-layout__loginLayout&quot;]/div[@class=&quot;LoginAgent-container__loginContainer&quot;]/div[@class=&quot;LoginAgent-container__loginImageSection&quot;]/div[@class=&quot;LoginAgent-container__twoColumns&quot;]/div[@class=&quot;LoginAgent-container__second&quot;]/div[@class=&quot;LoginAgent-container__loginFormSection&quot;]/div[@class=&quot;LoginAgent-container__loginFormContainer&quot;]/div[@class=&quot;LoginAgent-container__loginFormContent&quot;]/div[@class=&quot;AgentLogin-component__agentLoginComponent&quot;]/form[@class=&quot;AgentLogin-component__agentLoginFormComponent&quot;]/div[@class=&quot;AgentLogin-component__inputLogin&quot;]/fieldset[@class=&quot;AgentLogin-component__formGroup&quot;]/input[@class=&quot;AgentLogin-component__formControl&quot;]</value>
      <webElementGuid>566fb49a-28dd-4344-8ecd-d9bfaf44b36c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>9c6c031b-9f6f-4835-bcb5-fd395440336d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/form/div/fieldset/input</value>
      <webElementGuid>767c7d7f-12e2-4a1b-9ddd-967b8347e3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk menggunakan'])[1]/following::input[1]</value>
      <webElementGuid>4f6292b7-e475-440c-b77a-1ff652860879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kepentingan pribadi'])[1]/following::input[1]</value>
      <webElementGuid>d7de63a4-79ba-47cd-b395-013bf0e7a4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setuju dengan ketentuan yang berlaku'])[1]/preceding::input[2]</value>
      <webElementGuid>ac164168-02e4-472a-b46b-955bc3b5a894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::input[2]</value>
      <webElementGuid>8c1c7d5e-a185-40bd-9233-cb38997e2c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>01fbcb74-7a07-4cba-b262-a52fc301d4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukan Username' and @name = 'email']</value>
      <webElementGuid>15b7a41b-fb41-4853-b161-5ae44ecb80a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
