<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saya setuju_TnC</name>
   <tag></tag>
   <elementGuidId>79a2ebbf-827f-47a3-80e7-ec915d79e27f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TnC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TnC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>344b5590-d50f-487f-9e8b-3565f7be3f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>47c8ab5c-e31d-41e8-92f1-a986d1c38567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Checkbox-component__input</value>
      <webElementGuid>98646a5f-ec0b-4f63-98b0-36e8ef3589e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TnC</value>
      <webElementGuid>97007ce6-ff31-42d4-9d68-03f45dee7f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2c5a5c95-6715-4ae2-9e6f-121d097379e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TnC&quot;)</value>
      <webElementGuid>20c26ba3-60ca-498e-9675-244b522ff25a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TnC']</value>
      <webElementGuid>3529fc99-8a46-4946-ab49-96d69a852c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya setuju'])[1]/following::input[1]</value>
      <webElementGuid>a5e620d4-7817-4ac0-b493-d00841ad841e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ces@telkomsel.co.id'])[1]/following::input[1]</value>
      <webElementGuid>d71b2a68-145a-4d13-a17e-3c93ee45556f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klik disini untuk menunjukkan Anda telah membaca dan menyetujui Syarat dan Ketentuan'])[1]/preceding::input[1]</value>
      <webElementGuid>d9a68734-250a-4d66-9f60-30d511e35c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::input[1]</value>
      <webElementGuid>b058db9f-8e57-4526-9a7b-025f18429548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>304ef12b-6f6d-4d91-9eea-b31eeb9620c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TnC']</value>
      <webElementGuid>1a642849-1f92-4a4c-b01b-751b5cd56602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
