<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Completed</name>
   <tag></tag>
   <elementGuidId>d56f621b-f6b2-4656-a20b-a308ac208474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.MonitoringOrder-component__blue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div[2]/div/table/tbody/tr/td[9]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3c31f33e-7f8f-4c54-bc84-e030f8ca6195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MonitoringOrder-component__blue</value>
      <webElementGuid>ea3b4eb4-3ff8-45a5-ade7-d01fd2ed2d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completed</value>
      <webElementGuid>5ae37fd3-3ee0-4017-80e3-add6a739f9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;Customer-layout__appLayout&quot;]/div[@class=&quot;Customer-layout__container&quot;]/div[@class=&quot;Customer-layout__content Customer-layout__notDashboard&quot;]/div[@class=&quot;ManageOrder-container__manageOrderContainer&quot;]/div[@class=&quot;ManageOrder-container__manageOrderContent&quot;]/div[@class=&quot;MonitoringOrder-container__monitoringOrderContainer&quot;]/div[1]/div[2]/div[@class=&quot;Table-component__container&quot;]/table[@class=&quot;Table-component__table&quot;]/tbody[1]/tr[1]/td[9]/label[@class=&quot;MonitoringOrder-component__blue&quot;]</value>
      <webElementGuid>63570d11-6310-4399-9f41-0e5814a9ab42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div[2]/div/table/tbody/tr/td[9]/label</value>
      <webElementGuid>38c7f194-fb48-4fbb-864a-f64afa387fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREQ'])[1]/following::label[1]</value>
      <webElementGuid>48762635-34b0-48f1-a6f9-37841e00ccc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TC'])[1]/following::label[1]</value>
      <webElementGuid>f7515f8c-b122-46e4-bb7e-4611c11f8131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Register'])[1]/preceding::label[1]</value>
      <webElementGuid>c3dff8fa-0bec-462f-a31b-2edb53a5cc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WI'])[1]/preceding::label[1]</value>
      <webElementGuid>56534d7a-22ae-4b35-8a68-923ce99dec44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Completed']/parent::*</value>
      <webElementGuid>b5f517b8-87dd-4129-8658-48a8fa356386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/label</value>
      <webElementGuid>b73b3dc5-b0dc-41b2-9d7d-d07d221697a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Completed' or . = 'Completed')]</value>
      <webElementGuid>ee700a35-5efb-4ce2-b41f-f42f9e074abc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
