<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih paket anda_Select-arrow</name>
   <tag></tag>
   <elementGuidId>38aba982-106b-46c3-81f1-f8352c9925b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.Select-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/form/div/div[2]/fieldset/div/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>85721006-8fb6-4d58-a65e-6d3805511e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select-arrow</value>
      <webElementGuid>d667aceb-412f-4a12-9d54-6fd925b4042a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;Customer-layout__appLayout&quot;]/div[@class=&quot;Customer-layout__container&quot;]/div[@class=&quot;Customer-layout__content Customer-layout__notDashboard&quot;]/div[@class=&quot;AddOffer-component__addOfferComponent&quot;]/form[@class=&quot;AddOffer-component__addOfferFormComponent&quot;]/div[@class=&quot;AddOffer-component__inputGroup&quot;]/div[@class=&quot;AddOffer-component__dropdownContent&quot;]/fieldset[1]/div[@class=&quot;AddOffer-component__filterSelect&quot;]/div[@class=&quot;Select is-focused is-open is-searchable Select--single&quot;]/div[@class=&quot;Select-control&quot;]/span[@class=&quot;Select-arrow-zone&quot;]/span[@class=&quot;Select-arrow&quot;]</value>
      <webElementGuid>e2887faf-e696-499d-9fb1-f0b91a10e74e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/form/div/div[2]/fieldset/div/div/div/span/span</value>
      <webElementGuid>3583d98d-f1e8-4fb1-a899-6aa35c49cd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>f6c4b049-7b81-4d97-a990-128d8f7d5664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
